<!-- Standard -->
<ul class="small-block-grid-1 large-block-grid-3">
<?php foreach ($this->selectedImages as $image) : ?>
    <?php
    $image = (object) $image;
    $this->attributes->alt = $image->subline;

    echo '<li><a class="fancybox" href="'.Moraso_Html_Helper_Image::getPath($image->idart, $image->filename, 800, 600, 0, $this->attributes).'" data-fancybox-group="gallery" title="">';
    echo Moraso_Html_Helper_Image::getHtml($image->idart, $image->filename, $this->width, $this->height, $this->render, $this->attributes);
	echo '</a></li>';
    ?>
<?php endforeach; ?>
</ul>