<footer class="row" >
    <div class="large-12 columns">

        <hr />

        <div class="row" style="font-size: 0.75em">
            <div class="large-9 columns">
                <p>CASALPIN Ferienhütten GmbH | Gufer 67 A-L | A 6708 Brand | Telefon 0043 5559 22 5 10 | EMAIL <a href="mailto:anfrage@casalpin.com" target="_blank">anfrage@casalpin.com</a></p>
            </div>

            <div class="large-3 columns">
                <script type="application/x-moraso" src="Navigation:meta">
                    template = meta
                </script>
            </div>
        </div>
    </div>
</footer>