<!-- Head-Banner -->
<div class="hide-for-small row">
    <div id="featured" data-orbit data-options="timer_speed:2500; bullets:false;">
        <?php foreach ($this->selectedImages as $image) : ?>
            <?php
            $image = (object) $image;

            $this->attributes->alt = $image->subline;

            echo Moraso_Html_Helper_Image::getHtml($image->idart, $image->filename, $this->width, $this->height, $this->render, $this->attributes);
            ?>
        <?php endforeach; ?>
    </div>
</div>