<!DOCTYPE html>
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="de"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="de"> <!--<![endif]-->
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
        <script type="application/x-moraso" src="HTML.Meta.PageTitle">
            suffix = " | casalpin chalets"
        </script>

        <!-- BaseHref :: Start -->
        <script type="application/x-moraso" src="HTML.Meta.BaseHref"></script>
        <!-- BaseHref :: End -->

        <!-- CanonicalTag :: Start -->
        <script type="application/x-moraso" src="HTML.Meta.CanonicalTag"></script>
        <!-- CanonicalTag :: End -->

        <!-- Meta Tags :: Start -->
        <script type="application/x-moraso" src="HTML.Meta.Tags"></script>
        <!-- Meta Tags :: End -->

        <!-- Meta Geo Tags :: Start -->
        <meta name="geo.region" content="AT-8" />
		<meta name="geo.placename" content="Brand bei Bludenz" />
		<meta name="geo.position" content="47.102369;9.738228" />
		<meta name="ICBM" content="47.102369, 9.738228" />
        <!-- Meta Geo Tags :: End -->

        <!-- Windows 8 Tile :: Start -->
        <meta name="application-name" content="moraso CMS" /> 
        <!--<meta name="msapplication-TileImage" content="<?php echo Aitsu_Config::get('sys.webpath'); ?>skin/gfx/tileImage.png" />-->
        <meta name="msapplication-TileColor" content="#FFFFFF" />
        <!-- Windows 8 Tile :: End -->

        <!-- CSS :: Start -->
        <link rel="stylesheet" href="/skin/css/normalize.css" />
        <link rel="stylesheet" href="/skin/css/foundation.css">
        <link rel="stylesheet" href="/skin/css/compiled/app.css">
        <!-- CSS :: End -->

        <!-- JS :: Start -->
        <script src="/skin/js/vendor/prefixfree.min.js"></script>
        <script src="/skin/js/vendor/custom.modernizr.js"></script>
        <script src="/skin/js/jquery.js"></script>


        <script src="/skin/js/jquery.nicescroll.min.js"></script>
        <!-- JS :: End -->

        <!-- IE Fix for HTML5 Tags -->
        <!--[if lt IE 9]>
                <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
    </head>
    <body>
        <!-- End Google Tag Manager -->

        <!-- Header :: Start -->
        <script type="application/x-moraso" src="Template:Header">
            defaultTemplate = default

            template.default.name = Standard
            template.default.file = templates/header/default.phtml 
        </script>
        <!-- Header :: End -->
        
        <!-- Content :: Start -->
        <script type="application/x-moraso" src="Template:Content">
            defaultTemplate = default

            template.default.name = 1 Spalte
            template.default.file = templates/content/default.phtml 
            
            template.start.name = Startseite
            template.start.file = templates/content/start.phtml 
            
            template.2spalten.name = 2 Spalten
            template.2spalten.file = templates/content/two.phtml 
        </script>
        <!-- Content :: End -->

        <!-- Footer :: Start -->
        <script type="application/x-moraso" src="Template:Footer">
            defaultTemplate = default

            template.default.name = Standard
            template.default.file = templates/footer/default.phtml 
        </script>
        <!-- Footer :: End -->

        <!-- JS :: Start -->
        <script>
            document.write('<script src=' +
            ('__proto__' in {} ? '/skin/js/vendor/zepto' : '/skin/js/vendor/jquery') +
            '.js><\/script>');
        </script>
        <script src="/skin/js/foundation.min.js"></script>


	
        <script>
$(document).foundation('orbit', {
  timer_speed: 10000,
  pause_on_hover: true,
  resume_on_mouseout: true,
  animation_speed: 500,
  bullets: true});


        </script>
        <script>
        $(document).ready(
			function() {
				$("html").niceScroll();
			}
		);
        </script>
        <!-- JS :: End -->
        
        
    </body>
</html>
