<div class="row botborder header">
    <div class="large-3 columns">
		<a href="/" target="_self"><img src="/skin/images/casalpin.png" border="0" alt="CASALPIN" title="CASALPIN"></a>
    </div>
    <div class="large-7 columns">
        <script type="application/x-moraso" src="Image:banner">
            width = 1000
            height = 400
            template = config
        </script>
    </div>
    <div class="large-2 columns">
        Aktion
    </div>
</div>