<div class="row botborder header">
    <a href="/" target="_self">
    <div class="large-2 columns alpha omega" style="background: url(/skin/images/casalpin-neu.png) no-repeat top left; height: 100%; ">
		&nbsp; <!-- <img src="/skin/images/casalpin-neu.png" border="0" alt="CASALPIN" title="CASALPIN"> -->
    </div>
    </a>
    <div class="large-10 columns alpha omega" style="background: #FFF; height: 170px;">
        <script type="application/x-moraso" src="Image:banner">
            width = 835
            height = 170
            render = 2
            template = config
        </script>
    </div>

</div>