<div class="row botborder header">
    <div class="large-3 columns center">
		<a href="/" target="_self"><img src="/skin/images/casalpin.png" border="0" alt="CASALPIN" title="CASALPIN"></a>
		<br><br>
        de | en | it
    </div>
    <div class="large-9 columns alpha omega" style="background: #eeeeee; height: 170px;">
        <script type="application/x-moraso" src="Image:banner">
            width = 740
            height = 171
            render = 2
            template = config
        </script>
    </div>

</div>