<!-- boxenrechts -->
<?php if (count($this->articles) > 0): ?>
<?php foreach ($this->articles as $article) : ?>
    Teasertitle<br />
    <div class="large-12 columns" style="min-height: 100px; background: #d7d7d7; margin-bottom: 20px; color: white; ">
       <h1 style="color: white;"><?php echo $article->pagetitle; ?></h1>
	   <?php echo $article->content; ?>	
	</div>
<?php endforeach; ?>
<?php else: ?>
    <p>keine Artikel vorhanden</p>
<?php endif; ?>
