<!-- Standard -->
<?php if (count($this->articles) > 0): ?>
<div class="large-12 columns" style="min-height: 100px; padding-top: 0; margin-top: 0;">
<div class="row">
<?php foreach ($this->articles as $article) : ?>
<?php $idcat = Aitsu_Util::getIdCatByIdArt($article->idart); ?>
<a href="{ref:idcat-<?php echo $idcat; ?>}" target="_self">
<div class="large-4 columns alpha omega" style=" height: 200px; background: url(/image/200/200/0/<?php echo $article->idart; ?>/<?php echo $article->mainimage; ?>) no-repeat center center;">
	<span style="bottom: 10px; position: absolute; padding: 0 10px;"><h1 style="color: #fff;"><?php echo $article->pagetitle; ?></h1>
	<?php echo $article->content; ?>	
	</span>
</div>	  
</a>
<?php endforeach; ?>
</div>
</div>
<?php else: ?>
    <p>keine Artikel vorhanden</p>
<?php endif; ?>
