<div class="row large-12 cloumns topspace" style="margin-top: 20px;">
	<div class="large-2 columns">
		<script type="application/x-moraso" src="Navigation:main"></script>
		<br />
		<!-- de | en | it -->
	</div>

	<div class="large-8 columns">
		<div class="row ">
			<div class="large-12 columns botspace">
				<script type="application/x-moraso" src="Image:Bild">
				width = 1000
				height = config
				default.height = 400
				render = config
				template = config
				</script>
			</div>
		</div>
	
	
    	<div class="large-12 columns">
    	<div class="row ">
			<div class="headertext"><script type="application/x-moraso" src="HTML.Content:Header"></script></div>
        	<script type="application/x-moraso" src="HTML.Meta.PagetitleAsHeadline:Headline">
            	tag = h1
			</script>
			<hr />

			<script type="application/x-moraso" src="List.Articles:Port">
	        	categories = 20
                useOfStartArticle = 2
	            orderBy = created
	            template = portfolio
	            limit = 99
	            populateWith.headline.index = Headline
	            populateWith.bild.index = featured
	            populateWith.bild.type = property
	            populateWith.bild.index = ModuleConfig_featured:Image_Media
	        </script>


			<script type="application/x-moraso" src="HTML.Content:Content"></script>
            <script type="application/x-moraso" src="List.Download:PDFs"></script>
         </div>
      </div>   
	</div>
	
	<div class="large-2 columns">
		rechte spalte
	</div>
	
</div>