<div class="row large-12 cloumns topspace" style="margin-top: 20px;">
	<div class="large-2 columns">
		<script type="application/x-moraso" src="Navigation:main">		</script>
		<br />
		<!-- de | en | it -->
	</div>

	<div class="large-8 columns">
		<div class="row ">
			<div class="large-12 columns botspace">
				<script type="application/x-moraso" src="Image:featured">
				width = 1000
				height = config
				default.height = 400
				render = config
				template = config
				</script>
			</div>
		</div>
	
	
    	<div class="large-12 columns">
    	<div class="row ">
        	<script type="application/x-moraso" src="HTML.Meta.PagetitleAsHeadline:Headline">
            	tag = h1
			</script>
			<hr />
			<script type="application/x-moraso" src="HTML.Content:Content"></script>
			<script type="application/x-moraso" src="HTML.Content:Content_2"></script>

				

            <script type="application/x-moraso" src="List.Download:PDFs"></script>
            


         
         </div>
      </div>   
	</div>
	
	<div class="large-2 columns">
		rechte spalte
	</div>
	
</div>