<div class="row large-12 cloumns topspace" style="margin-top: 20px;">
	<div class="large-2 columns">
		<script type="application/x-moraso" src="Navigation:main"></script>
	</div>

	<div class="large-8 columns">
		<div class="row">
			<div class="large-12 columns">
				<script type="application/x-moraso" src="Image:featured">
				width = 1000
				height = config
				default.height = 400
				render = config
				template = config
				</script>
			</div>
		</div>
	
	
    	<div class="row large-12 columns">
        	<script type="application/x-moraso" src="HTML.Meta.PagetitleAsHeadline:Headline">
            	tag = h1
			</script>
			<hr />
			<script type="application/x-moraso" src="HTML.Content:Content"></script>
			<script type="application/x-moraso" src="HTML.Content:Content_2"></script>

            <script type="application/x-moraso" src="Image:Thumb_1">
                    width = 720
                    height = 720
                    render = 1
            </script>

            <script type="application/x-moraso" src="Image:Thumb_2">
                    width = 720
                    height = 720
                    render = 1
            </script>
         </div>
	</div>
	
	<div class="large-2 columns">
		rechte spalte
	</div>
	
</div>