<div class="row" style="padding: 0 10px;">
<div class="large-12 cloumns topspace" style="margin-top: 20px;">
	<div class="large-2 columns">
		<script type="application/x-moraso" src="Navigation:main"></script>
	</div>

	<div class="large-8 columns">
		<div class="row">
			<div class="large-12 columns">
				<script type="application/x-moraso" src="Image:featured">
				width = 1000
				height = config
				default.height = 400
				render = config
				template = config
				</script>
			</div>
		</div>
	
	
    	<div class="row large-12 columns">
        	<script type="application/x-moraso" src="HTML.Meta.PagetitleAsHeadline:Headline">
            	tag = h1
			</script>
			<hr />
			<script type="application/x-moraso" src="HTML.Content:Content"></script>
			<script type="application/x-moraso" src="HTML.Content:Content_2"></script>
         </div>
	</div>
	
	<div class="large-2 columns">
		<script type="application/x-moraso" src="List.Articles:BoxenRechts">
			categories = 17
			useOfStartArticle = config
			template = config
			default.template = boxenrechts
			populateWith.content.index = Content1
			populateWith.bild.index = Bild
			populateWith.bild.type = property
			populateWith.bild.index = ModuleConfig_bild:Image_Media
		</script>
	</div>
</div>
</div>


<div class="large-12 columns">
	<div class="row">
		<hr />
		<div class="large-2 columns">
		&nbsp;
		</div>
		<div class="large-8 columns">
		<script type="application/x-moraso" src="List.Articles:BoxenUnten">
		 	categories = config
		 	useOfStartArticle = config
		 	template = config
		 	default.template = Standard
		 	populateWith.content.index = Content1
		 	populateWith.bild.index = Bild
		 	populateWith.bild.type = property
		 	populateWith.bild.index = ModuleConfig_bild:Image_Media
		</script>
	</div>
	<div class="large-2 columns">
		&nbsp;
	</div>
	</div>
</div> 	