<div class="row large-12 cloumns topspace" style="margin-top: 20px;">
	<div class="large-2 columns">
		<script type="application/x-moraso" src="Navigation:main">		</script>
		<br />
		<!-- de | en | it -->
	</div>

	<div class="large-8 columns">
		<div class="row large-12 cloumns">
			<div class="small-6 columns">
				<script type="application/x-moraso" src="Image:featured">
				width = config
				default.width = 300
				height = config
				default.height = 400
				render = 1
				template = config
				</script>
			</div>
			<div class="small-6 columns">
				<script type="application/x-moraso" src="HTML.Content:Header"></script>
	        	<script type="application/x-moraso" src="HTML.Meta.PagetitleAsHeadline:Headline">
            		tag = h1
				</script>
				<hr>
				<script type="application/x-moraso" src="HTML.Content:Content"></script>
				
				<script type="application/x-moraso" src="List.Download:PDFs"></script>
			</div>   
		</div>
	</div>

	<div class="large-2 columns">
		rechte spalte
	</div>
	
</div>